//
//  DataTransferService.swift
//  Currex
//
//  Created by Serhan Khan on 20/01/2021.
//

import Foundation



public enum DataTransferError:Error{
    case noResponse
    case parsing(Error)
    case networkFailure(NetworkError)
    case resolvedNetworkFailure(Error)
}

public protocol DataTransferService{
    typealias CompletionHandler<T> = (Result<T,DataTransferError>)->Void
    
    
    @discardableResult
    func request<T: Decodable, E: ResponseRequestable>(with endpoint: E,
                                                       completion: @escaping CompletionHandler<T>) -> NetworkCancellable? where E.Response == T
    @discardableResult
    func request<E: ResponseRequestable>(with endpoint: E,
                                         completion: @escaping CompletionHandler<Void>) -> NetworkCancellable? where E.Response == Void
    
}

public protocol DataTransferErrorResolver{
    func resolve(error:NetworkError) -> Error
}

public protocol DataTransferErrorLogger {
    func log(error: Error)
}


public final class DefaultDataTransferService {
    
    private let networkService:NetworkService
    private let errorResolver:DataTransferErrorResolver
    private let errorLogger:DataTransferErrorLogger
    
    public init(networkService:NetworkService,errorResolver:DataTransferErrorResolver = DefaultDataTransferErrorResolver(),errorLogger:DataTransferErrorLogger = DefaultDataTransferErrorLogger()) {
        self.networkService = networkService
        self.errorResolver = errorResolver
        self.errorLogger = errorLogger
    }
}

extension DefaultDataTransferService:DataTransferService{
   
    public func request<T: Decodable, E: ResponseRequestable>(with endpoint: E,completion: @escaping CompletionHandler<T>) -> NetworkCancellable? where E.Response == T {

        return self.networkService.request(endpoint: endpoint) { result in
            switch result {
            case .success(let data):
                let result: Result<T, DataTransferError> = self.decode(data: data, decoder: endpoint.responseDecoder)
                DispatchQueue.main.async { return completion(result) }
            case .failure(let error):
                self.errorLogger.log(error: error)
                let error = self.resolve(networkError: error)
                DispatchQueue.main.async { return completion(.failure(error)) }
            }
        }
    }
    
    public func request<E>(with endpoint: E, completion: @escaping CompletionHandler<Void>) -> NetworkCancellable? where E : ResponseRequestable, E.Response == Void {
        return self.networkService.request(endpoint: endpoint) { result in
            switch result {
            case .success:
                DispatchQueue.main.async { return completion(.success(())) }
            case .failure(let error):
                self.errorLogger.log(error: error)
                let error = self.resolve(networkError: error)
                DispatchQueue.main.async { return completion(.failure(error)) }
            }
        }
    }
    
    
    // MARK: - Private
    private func decode<T: Decodable>(data: Data?, decoder: ResponseDecoder) -> Result<T, DataTransferError> {
        do {
            guard let data = data else { return .failure(.noResponse) }
            let result: T = try decoder.decode(data)
            return .success(result)
        } catch {
            self.errorLogger.log(error: error)
            return .failure(.parsing(error))
        }
    }
    
    private func resolve(networkError error: NetworkError) -> DataTransferError {
        let resolvedError = self.errorResolver.resolve(error: error)
        return resolvedError is NetworkError ? .networkFailure(error) : .resolvedNetworkFailure(resolvedError)
    }
    
    
}

//MARK: - Logger
public final class DefaultDataTransferErrorLogger:DataTransferErrorLogger{
    public init(){}
    
    public func log(error: Error) {
        printIfDebug("-------------")
        printIfDebug("\(error)")
    }
}

//MARK: - Error Resolver
public class DefaultDataTransferErrorResolver:DataTransferErrorResolver{
    public init(){}
    public func resolve(error: NetworkError) -> Error {
        return error
    }
}

//MARK: -
